// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type SceneCreate = {
    timestamp?: string;
    nv_document: {
        [key: string]: unknown;
    };
    tool_name: string;
    status?: string;
    result?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
};

export type ScenePublic = {
    timestamp?: string;
    nv_document: {
        [key: string]: unknown;
    };
    tool_name: string;
    status?: string;
    result?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
    id: string;
};

export type ScenesPublic = {
    data: Array<ScenePublic>;
    count: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ScenesReadScenesData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type ScenesReadScenesResponse = (ScenesPublic);

export type ScenesCreateAndProcessSceneData = {
    requestBody: SceneCreate;
};

export type ScenesCreateAndProcessSceneResponse = (ScenePublic);

export type ScenesReadSceneData = {
    id: string;
};

export type ScenesReadSceneResponse = (ScenePublic);

export type ScenesCreateSceneData = {
    requestBody: SceneCreate;
};

export type ScenesCreateSceneResponse = (ScenePublic);

export type UtilsHealthCheckResponse = (boolean);