"""allow nv_document in SceneUpdate

Revision ID: 0347281e50a5
Revises: 33dc74a9445f
Create Date: 2025-07-28 23:04:43.938005

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0347281e50a5'
down_revision = '33dc74a9445f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
