"""allow nv_document in SceneUpdate and make tool_name optional in SceneBase

Revision ID: 2d3cce9607a4
Revises: 0347281e50a5
Create Date: 2025-07-28 23:16:41.937836

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2d3cce9607a4'
down_revision = '0347281e50a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
